package shuangpin

var (
	// 微软双拼键位映
	msPinyinToKey = map[string]string{
		"b":    "b",
		"c":    "c",
		"d":    "d",
		"f":    "f",
		"g":    "g",
		"h":    "h",
		"j":    "j",
		"k":    "k",
		"l":    "l",
		"m":    "m",
		"n":    "n",
		"p":    "p",
		"q":    "q",
		"r":    "r",
		"s":    "s",
		"t":    "t",
		"w":    "w",
		"x":    "x",
		"y":    "y",
		"z":    "z",
		"ch":   "i",
		"sh":   "u",
		"zh":   "v",
		"a":    "a",
		"ai":   "l",
		"an":   "j",
		"ang":  "h",
		"ao":   "k",
		"e":    "e",
		"ei":   "z",
		"en":   "f",
		"eng":  "g",
		"i":    "i",
		"ia":   "w",
		"ian":  "m",
		"iang": "d",
		"iao":  "c",
		"ie":   "x",
		"iong": "s",
		"in":   "n",
		"ing":  ";",
		"iu":   "q",
		"o":    "o",
		"ong":  "s",
		"ou":   "b",
		"u":    "u",
		"ua":   "w",
		"uai":  "y",
		"uan":  "r",
		"uang": "d",
		// TODO fix me
		//   ue: ['t', 'v'],
		"ue": "t",
		"ui": "v",
		"un": "p",
		"uo": "o",
		"v":  "y",
		"ve": "v",
	}

	// 零声母微软双拼键位映射
	msSpecialPinyinToKey = map[string]string{
		"a":   "oa",
		"ai":  "ol",
		"an":  "oj",
		"ang": "oh",
		"ao":  "ok",
		"e":   "oe",
		"ei":  "oz",
		"en":  "of",
		"eng": "og",
		"er":  "or",
		"o":   "oo",
		"ou":  "ob",
	}
)
