package shuangpin

var (
	// 搜狗双拼键位映
	sougouPinyinToKey = map[string]string{
		"b":    "b",
		"c":    "c",
		"d":    "d",
		"f":    "f",
		"g":    "g",
		"h":    "h",
		"j":    "j",
		"k":    "k",
		"l":    "l",
		"m":    "m",
		"n":    "n",
		"p":    "p",
		"q":    "q",
		"r":    "r",
		"s":    "s",
		"t":    "t",
		"w":    "w",
		"x":    "x",
		"y":    "y",
		"z":    "z",
		"ch":   "i",
		"sh":   "u",
		"zh":   "v",
		"a":    "a",
		"ai":   "l",
		"an":   "j",
		"ang":  "h",
		"ao":   "k",
		"e":    "e",
		"ei":   "z",
		"en":   "f",
		"eng":  "g",
		"i":    "i",
		"ia":   "w",
		"ian":  "m",
		"iang": "d",
		"iao":  "c",
		"ie":   "x",
		"iong": "s",
		"in":   "n",
		"ing":  ";",
		"iu":   "q",
		"o":    "o",
		"ong":  "s",
		"ou":   "b",
		"u":    "u",
		"ua":   "w",
		"uai":  "y",
		"uan":  "r",
		"uang": "d",
		"ue":   "t",
		"ui":   "v",
		"un":   "p",
		"uo":   "o",
		"v":    "y",
		"ve":   "t",
	}

	// 零声母搜狗双拼键位映射
	sougouSpecialPinyinToKey = map[string][]string{
		"a":   {"o", "a"},
		"ai":  {"o", "l"},
		"an":  {"o", "j"},
		"ang": {"o", "h"},
		"ao":  {"o", "k"},
		"e":   {"o", "e"},
		"ei":  {"o", "z"},
		"en":  {"o", "f"},
		"eng": {"o", "g"},
		"er":  {"o", "r"},
		"o":   {"o", "o"},
		"ou":  {"o", "b"},
	}
)
